// <auto-generated />
namespace VehicleShowRoomManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Set_display_name_vehicle_and_customer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_display_name_vehicle_and_customer));
        
        string IMigrationMetadata.Id
        {
            get { return "202103311406041_Set_display_name_vehicle_and_customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
